### PR TITLE
fix wrong index in .subset2index

### PR DESCRIPTION
**Pull request by Yunuuuu**
As `features` is a factor, so `.subset2index` function will always return the first rows of the `object`

### CODE REVIEW

**Comment by alanocallaghan** [comment]
Another good catch, thanks! You can add yourself as a contributor in DESCRIPTION if you like, eg `person("firstname", "secondname", role=c("ctb"))`

**Comment by Yunuuuu** [comment]
Thanks @Alanocallaghan

**Comment by alanocallaghan** [comment]
Can you provide an example of code where this bug would occur? Just so I can write a test case.

**Comment by Yunuuuu** [comment]
because factor always subset the head elements, we just test this by indexing someone other than the heading elements
image

**Comment by Yunuuuu** [comment]
It'll be okay after merging this commit but failure in the present code. I just modified the existing test code, can this make sense ? or should I add a new test section ?

**Comment by alanocallaghan** [comment]
Thanks, that's perfect! I copied this code to #182  as I ended up patching subset2index rather than handling it on the scater end. Thanks again for the great contributions, really appreciated

**Pull request closed without merging**
