### PR TITLE
include eig and GOF from cmdscale as attr in result of calculateMDS

### PR DESCRIPTION
**Pull request by FelixErnst**

### CODE REVIEW

**Comment by alanocallaghan** [comment]
I usually forget as well but could you bump version/date in description and update inst/NEWS.rd in future?

**Comment by FelixErnst** [comment]
I updated the branch, but it doesn't appear to be picked up by GH. 

Should I open a new PR?

**Comment by FelixErnst** [comment]
Ah ok the merge still got through. Thanks!

**Comment by alanocallaghan** [comment]
Yeah I'd already merged it and updated myself, no worries

**Pull request merged**
