### PR TITLE
Various fixes to read10xResults

### PR DESCRIPTION
**Pull request by LTLA**
In response to #5. Clearly our current tests and checks are not sufficient. Need to add a check for loading in multiple directories in `data_dir` (even if it is the same one twice), and to check that the filtering functions work as intended.

### CODE REVIEW

**Comment by davismcc** [comment]
Thanks, Aaron.

**Comment by danfulop** [comment]
Is there a way to install the current snapshot of scater with `devtools::install_github("davismcc/scater")`, **but** on R 3.4.x?  I'm asking because I'd like to get these fixes related to 10X data.

I'm guessing there might be a way to disable the R version check. The package seemed to install without a problem, and then at the end aborted and removed the package because the R version was lower than 3.5

**Comment by danfulop** [comment]
For now I just sourced a renamed copy of the fixed `read10xResults()`, as my only issue is being able to read in several batches/conditions together; the data is being read in as a dgCMatrix in my case.

**Comment by LTLA** [comment]
The latest version of _scater_ on Bioconductor (1.6.1) should already be patched.

**Comment by danfulop** [comment]
Hmmm, I am running scater 1.6.1 and experiencing the issue with loading several batches/conditions (from one 10X experiment) together. The hack I mentioned above is working, though.

**Comment by LTLA** [comment]
Yes, on further examination, it seems like the fixed `read10xResults` hasn't made it into 1.6.1.

@davismcc?

**Pull request merged**
